### ISSUE TITLE
Columns and rows - swap them

### ISSUE THREAD

**Issue by andrelec1** [klattiation/gridl#15]
I have a grid like :
```
const data = [
    [ 1, 2, 3],
    [ 6, 7, 8],
    [10,11,12],
    [15,16,17],
    [20,21,22],
];
```
i want this :
```
const data = [
    [ 1, 6, 10, 15, 20],
    [ 2, 6, 11, 16, 21],
    [ 3, 8, 12, 17, 22],
];
```

When i read the readme, i see : Columns and rows - swap them
That sound exatly why i need but i can't find the function :/ 
I have another choice thant rotate the matrice and miror verticaly ?

**Comment by klattiation** [comment]
You could rotate it one step counterclockwise and then flip it on the x-axis.

```
const data = [
    [ 1, 2, 3],
    [ 6, 7, 8],
    [10,11,12],
    [15,16,17],
    [20,21,22],
];
const newData = gridl(data)
	.rotate(-1)
	.flipX()
	.data();
```

**Comment by klattiation** [comment]
Swapping means to take two rows **or** two columns and swap their position within the grid.
See also: https://klattiation.github.io/gridl/gridl/latest/tutorial-swapping.html

**Comment by andrelec1** [comment]
i use the same approach but in the other direction: `this.#gridl = gridl(csvData).rotate(1).flipY();`

i'm talking about this : 
![image](https://user-images.githubusercontent.com/3273204/73744628-7d664980-4751-11ea-8d9b-50504064d62c.png)

For me each things is like scoped in their category ^^
And i thinkings is two separate things ...

**Comment by klattiation** [comment]
Oh I see, maybe the documentation is a bit redundant and confusing here... Thanks for pointing that out! I'll adapt the readme at that point.
